### ISSUE TITLE
支持Acfun的json

### ISSUE THREAD

**Issue by cnbeining** [jabbany/ABPlayerHTML5#10]
从抓包来看，还是libxml.js导入了弹幕文件。

这肯定是不能用JSON了。

但是从CommentCore来看应该是可以用JSON的。

希望啥时候写一个JSON的例子。。。

**Comment by LilHayah** [comment]
A站的弹幕从这儿下：
'http://static.comment.acfun.mm111.net/'  +  data-vid
比如
http://static.comment.acfun.mm111.net/2046619

**Comment by jabbany** [comment]
卧槽好老的贴了，不过还是要挖一下坟。
之前有机会终于好好逆向了一下A站格式（不过这是17年的事情了，不知道A站会不会再改）。

格式文档在这里： https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/data-formats/acfun-json.md
应该是目前最完整的了。

这个格式现在CCL部分支持了，有的（比如锚点、滤镜、3D旋转动画）还不能完全支持。
