### ISSUE TITLE
怎么用ABplayerHTML5发送弹幕？

### ISSUE THREAD

**Issue by mountainguan** [jabbany/ABPlayerHTML5#15]
我把它以播放器接口的方式搭建在了校园内网~好多人说希望可以发送弹幕，可是我不知道怎么做，即使本地建立数据库也可以的= =主要是我想知道怎么做，谢谢

**Comment by jabbany** [comment]
发送弹幕其实不难，ABPInst会返回一个叫  txtText 的 HTML 元素，这就会是文本框。只要在这个元素上去 addEventListener 添加一个键盘操作（比如keyup等等），然后判断是否是 enter 来确认是否发送弹幕。

发送弹幕的时候根据输入的内容创建一个弹幕的表示形式。目前UI上没设计能改弹幕类型/大小和颜色的部件，不过如果有的话这些可能都会是参数。

    var absDan = {}; //用于存放弹幕属性
    absDan["mode"] = 1; //决定采取什么mode，比如1是普通滚动等等，详细请看 CommentCoreLibrary文档里面的弹幕类型介绍
    absDan["text"] = getDanmakuText(); //通过某种渠道获取文字
    absDan["color"] = 0xffffff; //获取颜色（为一个数字）
    absDan["size"] = 25; // 想办法获取字号
    absDan["stime"] = video.curentTime(); // 通过某种方法获取当前视频的播放位置
    ...

之后可以加上 `["border"]=true`，然后调用 `inst.cmManager` 的 `send` 来派发弹幕到显示界面。同时通过 AJAX 把这些抽象的数据发送到服务器。服务器端用某个实现解读你发过去的参数然后更新弹幕数据库等等。

服务器端和中间post的格式都比较自由，所以没有什么建议的方法。只要能保证该到的必要数据都有就可以了（比如视频ID等等）。

**Comment by mountainguan** [comment]
是这样的～我学校是限制流量的，所以我把播放器用php通过参数传递电脑的mp4文件和弹幕迟xml文件。也就是说弹幕和视频都是已经本地化了的，然后我不知道有没有什么现成的函数可以直接实现发送本地弹幕。类似于别人发送了一个弹幕，然后我本地的XML就更新那样………

**Comment by jabbany** [comment]
现成的PHP实现不知道有没有，保存弹幕的实现没怎么见到，大概有 http://www.missevan.cn/ 。基本上你想做的事情大概要：

1. 创建一个弹幕用的数据库
2. 导入XML到数据库
3. 新发的弹幕加到数据库中
4. 获取弹幕时从数据库读出为JSON或XML等格式

另外，这个文章里有实时弹幕的实现，应该对发送弹幕的前端逻辑有所帮助。http://www.stackess.com/index.php/archives/23/

**Comment by moehub** [comment]
关于inst.cmManager这个有详细说明吗？

**Comment by jabbany** [comment]
cmManager在这里就是一个 CommentManager 实例，参考 https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentManager.md
