### ISSUE TITLE
将刚发送的弹幕到显示界面是不是这样？

### ISSUE THREAD

**Issue by csacx** [jabbany/ABPlayerHTML5#16]
<code>inst.cmManager.send(ABPInst.txtText.value);</code>

但是这样不行啊，求问如何才能将刚发送弹幕立即显示到界面

**Comment by csacx** [comment]
<code>inst.cmManager.send(ABPInst.txtText.value);</code>

**Comment by csacx** [comment]
作为回报，我教你找原盘资源吧

**Comment by jabbany** [comment]
cmManager 接受的是一个抽象弹幕对象。这个可以参考 CommentCoreLibrary里面的[相关文档](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentProperties.md)。

基本上来说就是要传入一个 Object:
````JavaScript
{
  'text': "这里是弹幕的内容",
  'mode': 1,  // 弹幕类型，滚动
  'stime': xxx, //视频开始时间（用于计算弹幕的碰撞位置）
  'size': 25,  //普通大小
  'color': 0xffffff, // 白色
  'border': true  // 显示边框
}
````
等等。当然这样 `send()` 的弹幕在回播的时候就没了，所以还得找一些办法把弹幕加入弹幕列表。这个可以在发送到服务器后通过接受回复完成，或者手动完成后等待服务器同步。

**Comment by csacx** [comment]
存入列表这么复杂先搞不懂，先教我简单实现吧，ajax存储弹幕，我已经没问题了。就差怎么将刚发送的弹幕显示出来，我获取到了<code>ABPInst.txtText.value</code>,怎样才能将它显示出来。<code>inst.cmManager.send(ABPInst.txtText.value)</code>这样不行啊

**Comment by csacx** [comment]
就是<code>.send(object)</code>就是send要send一个完整的对象吗？一个字符串是不行的？

**Comment by csacx** [comment]
明白了，我去试一下

**Comment by csacx** [comment]
成功了，原来不是<code>.send()</code>而是<code>.sendComment()</code>。

**Comment by csacx** [comment]
非常感谢解惑，有想要的动漫资源可以找我啊，嗯基本都能找到

**Comment by jabbany** [comment]
不用谢～有问题欢迎随时来问=w=
