### ISSUE TITLE
为什么弹幕加载不进来呢？

### ISSUE THREAD

**Issue by BanAugust** [jabbany/ABPlayerHTML5#17]
最近正在学习这个项目，不过代码下到本地之后为什么没有弹幕，只有视频在播放？
大家有没有遇到过这个问题？

**Comment by manageryzy** [comment]
ajax需要服务器环境

**Comment by cnbeining** [comment]
你需要个东西加载，否则安全策略会拦住你。

弄个XAMPP或者MAMP/MNMP。。

**Comment by BanAugust** [comment]
嗯，弄好了，谢谢ls们~
