### ISSUE TITLE
请问关于本项目的相关文档到哪里查看？

### ISSUE THREAD

**Issue by moehub** [jabbany/ABPlayerHTML5#19]
RT。。貌似我并没有找到关于本项目比较全的文档，关于inst的一些用法也不得而知。。请问我该去哪里查看

**Comment by jabbany** [comment]
目前有这个 https://github.com/jabbany/ABPlayerHTML5/blob/master/docs/ABPlayerInstance.md
inst 基本上就是一些裸 HTML DOM元素+CCL绑在一起。。。有关CCL的用法和API，参考 https://github.com/jabbany/CommentCoreLibrary
