### ISSUE TITLE
目前是使用css3动画的吗?

### ISSUE THREAD

**Issue by whstudy** [jabbany/ABPlayerHTML5#20]
目前是使用css3动画的吗?

**Comment by jabbany** [comment]
`dev-cssonly`分支上是的。`master`还是基于timer的动画。

**Comment by jabbany** [comment]
就是现在checkout的话是基于timer的，然后，可以手动checkout CommentCoreLibrary的dev-cssonly分支，取代默认的CCL文件，然后就是基于CSS的了。

CSS有的设备上不稳定所以没纳入master。

**Comment by whstudy** [comment]
设备是移动设备吗?  手机上好象一些浏览器和系统会直接接管播放器,没办法显示弹幕?

**Comment by jabbany** [comment]
嗯，ios和Symbian就会接管视频通过系统播放器播。这个Webapp都是没法解决的。
CSS动画有的手机浏览器支持不全，所以有的设备上不work，但是如果面向Chrome或者Firefox的话，CSS3模式的弹幕应该是没问题的

**Comment by whstudy** [comment]
嗯,是的,电脑上的话,只要支持h5的基本上都能支持弹幕,比较麻烦的就是手机端,很多浏览器会接管视频播放

**Comment by whstudy** [comment]
关键公司的项目也主要是在微信端,webapp端
