### ISSUE TITLE
a站在微信里不能显示弹幕，b站可以

### ISSUE THREAD

**Issue by whstudy** [jabbany/ABPlayerHTML5#23]
想知道怎么实现的

**Comment by jabbany** [comment]
具体不太清楚，目前只知道技术上B站在移动浏览器上的弹幕方案是基于CSS的，类似CCL的css-only branch。效果还性，B站的方案大概比CCL轻量级一些，不过似乎不支持高级弹幕（只有滚动和顶部底部）

至于微信端有没有弹幕（技术上），以及站点有没有选择加弹幕（运营上）之类的，就不太清楚了。

**Comment by whstudy** [comment]
这两天再看,发现B站也显示不了弹幕了,也变成微信自带的播放器接管了
