### ISSUE TITLE
如果能支持HLS的话，就完美了

### ISSUE THREAD

**Issue by cccRaim** [jabbany/ABPlayerHTML5#24]

**Comment by cnbeining** [comment]
是否支持hls不由播放器而定。弹幕渲染和视频没有关系。

请参考hls.js和Safari。

一个实现可以看我的ABP-Py，提供了大部分浏览器的基本原生hls支持。

2016年5月11日星期三，陈然 <notifications@github.com> 写道：

**Comment by cccRaim** [comment]
感谢cnbening指点，已实现直播，目前在摸索怎么调用函数发弹幕- -

**Comment by jabbany** [comment]
考虑看看这个系统？ http://cnodejs.org/topic/54fd8d4a1e9291e16a7b3598
（感觉写得还是挺靠谱的）和这个文档 https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/DoingItRight.md#实时弹幕支持-live-comments

**Comment by jabbany** [comment]
卧槽，Github还能点攒了？

**Comment by cccRaim** [comment]
哈哈，我也才发现。感谢指点，文章很有用

**Comment by cnbeining** [comment]
还是我的那个repo 有发弹幕功能。

自己随便找个后端就是。

2016年5月12日星期四，陈然 <notifications@github.com> 写道：

**Comment by cccRaim** [comment]
谢谢各位指点，我已经实现了，直播➕弹幕
