### ISSUE TITLE
火狐下面b站用这弹幕速度有点快啊。。。不然还想做个自用的html5脚本

### ISSUE THREAD

**Issue by a1018148046** [jabbany/ABPlayerHTML5#25]

**Comment by cnbeining** [comment]
看下我的一个ABP-Py 可以调速度。

之前有这个issue。

2016年5月14日星期六，a1018148046 <notifications@github.com> 写道：

**Comment by jabbany** [comment]
参考： https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/DoingItRight.md#弹幕速度-comment-default-speed

直接获取 ABPlayerHTML5绑定后的instance里面的cmManager，然后按照上面的文档设置运行速度延长/缩短就可以了。或者也可以采取缩放弹幕的方法（在那个文档往下一点的部分）。
