### ISSUE TITLE
能不能限制同屏的弹幕数量呢 太多的量火狐cpu狂飙了 

### ISSUE THREAD

**Issue by a1018148046** [jabbany/ABPlayerHTML5#27]

**Comment by jabbany** [comment]
可以，参考 https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentManager.md
在返回的 inst 里面把 cmManager 的 options.limit 设置上应该就能限制同屏弹幕。

**Comment by a1018148046** [comment]
设置了一下 除了数字0是无限制 其他整数弹幕显示都为0了。。。

**Comment by jabbany** [comment]
这。。。可能是bug。。。我得研究一下。

**Comment by jabbany** [comment]
哦，这个被修了！在这里也给关掉。
果然是有bug！
