### ISSUE TITLE
请问支持HLS吗

### ISSUE THREAD

**Issue by since66** [jabbany/ABPlayerHTML5#28]
是否支持HLS？

**Comment by cnbeining** [comment]
是否支持HLS和弹幕渲染无关。

给你个提示：

https://github.com/cnbeining/ABPlayerHTML5-Py/blob/master/webpage_live_temple.html#L39-L43

**Comment by jabbany** [comment]
楼上正解，HLS支持主要看浏览器支持和HLS库。一般移动端浏览器普遍都直接支持hls，桌面浏览器有js库可以支持。

相关HLS的实现可参考：
https://github.com/dailymotion/hls.js/tree/master
