### ISSUE TITLE
安卓下弹幕似乎会被播放器盖住，有什么解决方案？

### ISSUE THREAD

**Issue by wudongyang** [jabbany/ABPlayerHTML5#30]
现在的手机在安卓微信下访问 ABPlyerHTML5 反而会有问题，看现象似乎是播放器把弹幕盖住了。
好像很多浏览器也是同样的现象。

iOS 的微信客户端反而可以通过设置 webkit-playsinline 来实现弹幕。

**Comment by jabbany** [comment]
安卓chrome下测试demo没法重现。都有哪些浏览器有这个问题？
播放器弹幕部分是动态载入的，或许有的浏览器不支持一些JS功能。如果是遮盖问题可以尝试把弹幕层对象的CSS类里面zindex设高一点看看是不是还发生问题。

**Comment by wudongyang** [comment]
微信，QQ浏览器，UC浏览器，小米自带的浏览器都不行。Chrome 确实没问题。
现在好像好多都是用自己内置的播放器去管理video标签，zindex也不好用。

**Comment by jabbany** [comment]
用自己内置播放器管理video那就没辙了。
只能提示用户换个符合HTML5标准的浏览器进行浏览。
