### ISSUE TITLE
当屏幕缩小时，能否统一把弹幕也缩小

### ISSUE THREAD

**Issue by wudongyang** [jabbany/ABPlayerHTML5#31]
现在测试发现好像屏幕虽然小了，但弹幕还是按照xml中的字体去显示，这样就导致了弹幕太大。

看文档也没有找到相应的处理方法。

**Comment by jabbany** [comment]
https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/DoingItRight.md#弹幕字号和速度同步拉伸-autoscale-comment

**Comment by jabbany** [comment]
简单讲就是监屏幕变化，然后scale整个弹幕舞台容器。。。

**Comment by wudongyang** [comment]
哦，在这里，感谢。
