### ISSUE TITLE
怎么播放分段视频

### ISSUE THREAD

**Issue by weituotian** [jabbany/ABPlayerHTML5#32]
比如说服务器有一个视频video,它被分成了几段,video_1.mp4, video_2.mp4, video_3.mp4等等, 怎么无缝切换分段?支持吗?

**Comment by cnbeining** [comment]
考虑用个hls.js包一下？

**Comment by weituotian** [comment]
@cnbeining 不用无缝切换,简单切换就好了,可以做到嘛?

**Comment by jabbany** [comment]
理论上应该不难。。。？ABPlayerHTML5这个只有一个类似分P的模式（就是通过 playlist，在demo页面有示例）但是不是面向多分段的。

感觉自己实现的话就是需要有个东西能提供分段拼接metadata（指定分段的顺序和长度），然后建立两个video元素，在上一个播的时候自动buffer下一个，上一个触发stop就直接start下一个然后隐藏上一个视频之类的。。。时间轴也要单独处理一下。有点类似 https://github.com/jabbany/ABPlayer/blob/master/src/org/kanoha/video/NSComponent.as 这个（模式取自 PAD播放器）

不过感觉大概用 hls.js 包一下比较有未来可维护性。

**Comment by jabbany** [comment]
清理以下Issue
有关HLS可以参考 #28
