### ISSUE TITLE
播放时如何重新载入弹幕 或 插入弹幕

### ISSUE THREAD

**Issue by player819** [jabbany/ABPlayerHTML5#34]
弹幕一开始加载后 如果有用户新增评论 要怎么处理

**Comment by cnbeining** [comment]
一个缺德的办法：模拟一个新用户 发送弹幕 这样就不会出框框。用于某死了的项目。

**Comment by jabbany** [comment]
用 CCL 提供的 insert 可以把弹幕信息插入时间轴。参考 [CommentManager.insert](https://github.com/jabbany/CommentCoreLibrary/blob/master/docs/CommentManager.md#insertdataicommentdata)。
