### ISSUE TITLE
一直报错  TypeError: Failed to fetch

### ISSUE THREAD

**Issue by wjsw1781** [jabbany/ABPlayerHTML5#38]
<video id="load-player"></video>

<script>
    var inst = ABP.create(document.getElementById('load-player'), {
        'src': 'https://vip.okokbo.com/20171220/xf6ducsR/800kb/hls/index.m3u8',
        'width': 800,
        'height': 600
    });
    (new CommentLoader(inst.cmManager)).setParser('BilibiliParser').load('GET', 'https://api.bilibili.com/x/v1/dm/list.so?oid=57224830');
   
</script>

**Comment by jabbany** [comment]
这是个API问题（Fetch远程资源被禁止），我猜 Bilibili 的 API 服务器上有白名单，不允许随便跨域 CORS请求。你可以试试load自己域名下的资源，或者写个自己域名下的代理脚本来在服务器端请求B站API。。。
